"""
Django settings for gtmarker project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from pathlib import Path
import numpy as np
import shutil
from gtm_hit.misc.wildtrack_calib import load_calibrations
from gtm_hit.misc.utils import read_calibs, get_frame_size
from gtm_hit.misc.scout_calib import load_scout_calib

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%z1g%^3%nf-k3sf$i^qra_d*0m4745c57f&(su(2=&nuwt#=z1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['127.0.0.1']
ALLOWED_HOSTS = ['10.90.43.13', 'pedestriantag.epfl.ch','localhost','127.0.0.1', '0.0.0.0',"192.168.100.23", "iccvlabsrv15.iccluster.epfl.ch"]

# Application definition

INSTALLED_APPS = [
    'marker.apps.MarkerConfig',
    'gtm_hit.apps.Gtm_hitConfig',
    #'gtm_hit',
    'home',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrapform',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'marker.middleware.RequireLoginMiddleware',
]
LOGIN_REQUIRED_URLS = (
    r'/marker/(.*)$',
)
LOGIN_REQUIRED_URLS_EXCEPTIONS = (
    r'/marker/login(.*)$',
    r'/marker/logout(.*)$',
)

LOGIN_URL = '/login/'

ROOT_URLCONF = 'gtmarker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gtmarker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
#
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'scout',
        'USER': 'scout',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '',
    }
}
DATA_UPLOAD_MAX_NUMBER_FIELDS = None
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'mydatabase', # This is where you put the name of the db file. 
#                  # If one doesn't exist, it will be created at migration time.
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'pedestriantag',
#         'USER': 'pedestriantag',
#         'PASSWORD': 'lAzyLift96',
#         'HOST': 'localhost',
#         'PORT': '',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

print(BASE_DIR) 
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join('gtm_hit/static')

#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'gtm_hit'),)

# Additional locations of static files
#STATICFILES_DIRS = [
#location of your application, should not be public web accessible 
# os.path.join(BASE_DIR, '/home/static/'),
# os.path.join(BASE_DIR, '/gtm_him/static/'),
# os.path.join(BASE_DIR, '/marker/static/')
#]

SAVES = '/labels/'

# Constants
#
# f_rect = open('./marker/static/marker/cst.txt', 'r')
# lines = f_rect.readlines()
# f_rect.close()
# NB_WIDTH = int(lines[2].split()[1])
# NB_HEIGHT = int(lines[3].split()[1])
# NB_RECT = NB_WIDTH * NB_HEIGHT
# MAN_RAY = float(lines[4].split()[1])
# MAN_HEIGHT = float(lines[5].split()[1])
# REDUCTION = float(lines[6].split()[1])
# NB_CAMS = int(lines[9].split()[1])

DELTA_SEARCH = 5

#TEMPLATES[0]['OPTIONS']['context_processors'].append("marker.context_processors.rectangles_processor")

# try:
#     rectangles_file = './marker/static/marker/rectangles.pom'#480x1440.pom'
#     f_rect = open(rectangles_file, 'r')
#     lines = f_rect.readlines()
#     f_rect.close()
#     if lines[0].split()[0] != "WIDTH":
#         messagebox.showerror("Error","Incorrect file header")
#     else:
#         NB_WIDTH = int(lines[2].split()[1])
#         NB_HEIGHT = int(lines[3].split()[1])
#         NB_RECT = NB_WIDTH * NB_HEIGHT
#         MAN_RAY = float(lines[4].split()[1])
#         MAN_HEIGHT = float(lines[5].split()[1])
#         REDUCTION = float(lines[6].split()[1])
#         NB_CAMS = int(lines[9].split()[1])
#         incr = 0
#         test = []
#         FIND_RECT = [[{} for _ in range(2913)] for _ in range(NB_CAMS)]
#         RECT = [{} for _ in range(NB_CAMS)]
#         for line in lines[10:]:
#             l = line.split()
#             cam = int(l[1])
#             id_rect = int(l[2])
#             if l[3] != "notvisible":
#                 a, b, c, d = l[3:]
#                 a = int(a)
#                 b = int(b)
#                 c = int(c)
#                 d = int(d)
#                 ratio = 180/(d-b)
#                 if d < 5000:
#                     if abs(c - a) < abs(d - b):
#                         RECT[cam][id_rect] = (a, b, c, d,ratio)
#                         FIND_RECT[cam][d][(a + c) // 2] = id_rect
#         # NB_CAMS = 4
# except FileNotFoundError:
#         print("Error: Rectangle file not found")



# DSETNAME = "rayon4"
# CAMS = ["cam1","cam2","cam3","cam4"]
# FRAME_SIZES = get_frame_size(DSETNAME, CAMS, STARTFRAME)
# CALIBS = read_calibs(Path("./gtm_hit/static/gtm_hit/dset/"+DSETNAME+"/calibrations/full_calibration.json"), CAMS)
# NB_CAMS = len(CAMS)

# need to: establish symlinked folders for get frame size etc
DSETNAME = "SCOUT"
# WORKER_ID = 'NEWCALIBMESH'
DSETPATH = Path("./gtm_hit/static/gtm_hit/dset/") / DSETNAME
SYMLINK_DEST_FRAMES = DSETPATH / "frames"
SYMLINK_SOURCE_FRAMES = Path('/cvlabscratch/home/engilber/datasets/SCOUT/collect_30_05_2024/sync_frame_seq_1')
CALIBPATH = DSETPATH / "calibrations"
CALIB_SRC = Path("/cvlabdata2/home/grosche/dev/calib/initial_calibration")
# CALIB_SRC = Path("/cvlabscratch/home/engilber/datasets/SCOUT/collect_30_05_2024/sync_frame_seq_1/calibrations/calibrations")
FPS = 1 # framerate of input video (note, assumes 10fps base)
NUM_FRAMES = 12000
FRAME_START = 0
FRAME_END = FRAME_START + NUM_FRAMES
HEIGHT = 1.8
RADIUS = 0.5 #person radius
FLAT_GROUND = False#True # Whether or not to use the mesh for dataset generation and annotation
FRAME_SKIP = int(float(10 / FPS))
TIMEWINDOW = 5 * FRAME_SKIP # cropped frames loaded when selecting a bounding box (on either side)

VALIDATIONCODES = []
STARTFRAME = 2
NBFRAMES = NUM_FRAMES + 10
LASTLOADED = 0
INCREMENT = FRAME_SKIP
UNLABELED = list(range(0,NBFRAMES,INCREMENT))

STEPL = 0.02
MOVE_STEP = 0.02 #same as stepl vidis ovoDA
SIZE_CHANGE_STEP=0.03
# NOTE: run data creation with full cameras before bed!
try:
    CAMS = [Path(cam).name.replace('_0.json', '') for cam in CALIBPATH.iterdir()]
except FileNotFoundError:
    CAMS = [Path(cam).name.replace('_0.json', '') for cam in CALIB_SRC.iterdir()]
    #["cam1","cam2","cam3","cam4","cam5","cam6","cam7","cam8"]

# Reorder CAMS according to desired order
order = [f'cvlabrpi{i}' for i in [10,21,13,12,7,19,24,5,23,3,2,4,1,22,11,8,26,17,14,25,6,9,18,15,16]]
assert len(order) == len(CAMS) and len(set(order)) == len(order), "Order and CAMS must have the same length and unique elements"
CAMS = [cam for cam in order if cam in CAMS]

print(f"CAMS: {CAMS}")
print(CAMS)
FRAME_SIZES = get_frame_size(DSETNAME, CAMS, STARTFRAME)
#CALIBS = read_calibs(Path("./gtm_hit/static/gtm_hit/dset/"+DSETNAME+"/calibrations/full_calibration.json"), CAMS)
NB_CAMS = len(CAMS)
CALIBS= load_scout_calib(CALIBPATH, cameras=CAMS, calib_source_path = CALIB_SRC)
ROTATION_THETA = np.pi/24
UNDISTORTED_FRAMES=False
MERGE_THRESHOLD = 1.0
MAX_OUTLIER_GAP = 4
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MESHPATH = Path("/cvlabscratch/home/engilber/datasets/SCOUT/collect_30_05_2024/scene_dense_textured_cleanup.ply")
EXPORT = False
if not EXPORT:
    MESHPATH = '/cvlabscratch/home/engilber/datasets/SCOUT/collect_30_05_2024/mesh_ground/mesh_ground_no_text.ply'
    # MESHPATH = '/cvlabscratch/home/engilber/datasets/SCOUT/collect_30_05_2024/scene_dense_textured_cleanup.ply'#Path("/cvlabdata2/home/grosche/dev/calibration") \
        # / "scene_dense_texturet_decimate_1_manual_cleanup.ply"
    import trimesh
    try:
        import trimesh.ray.ray_pyembree
    except:
        print("It's going to be slow")
    MESH = trimesh.load(MESHPATH)

import json
from shapely.geometry import Polygon
from gtm_hit.misc.geometry import get_polygon_from_points_3d



ROIjson = json.load(open('/cvlabdata2/home/grosche/dev/calibration/ROI_annotated_polygon_3.json'))

ROI = {}
# for cam_name, polygon in ROIjson['points_3d'].items():
#     ROI[cam_name] = get_polygon_from_points_3d(polygon)
from gtm_hit.misc.geometry import reproject_to_world_ground_batched
for cam_name, polygon in ROIjson['points_2d'].items():
    # project 2d points to 3d
    ground_pix = np.array(polygon)
    K0, R0, T0, dist = CALIBS[cam_name].K, CALIBS[cam_name].R, CALIBS[cam_name].T, CALIBS[cam_name].dist
    polygon_3d = reproject_to_world_ground_batched(ground_pix, K0, R0, T0, dist)
    ROI[cam_name] = get_polygon_from_points_3d(polygon_3d)


OFFSETS = {'cvlabrpi11': 23, 'cvlabrpi22': 10}
import re
# def get_frame_path_dict(dset = DSETNAME, frame_path = SYMLINK_DEST_FRAMES, cams = CAMS, local_path = None):
#     """
#     Create dictionary of frame paths for each camera
#     """
#     if local_path is None:
#         lookup_path = frame_path
#     else:
#         lookup_path = local_path
#     frame_path_dict = {}
#     # Use os.scandir for efficient directory traversal
#     for cam_folder in os.scandir(lookup_path):
#         cam_name = cam_folder.name
#         if cam_folder.is_dir():
#             for file in os.scandir(cam_folder.path):
#                 if file.is_file() and file.name.endswith(".jpg"):
#                     match = re.search(r"_(\d+)\.jpg$", file.name)
#                     if match:
#                         index = int(match.group(1))
                        
#                         adjusted_index = max(0, index + OFFSETS.get(cam_name, 0))

#                         if adjusted_index != index:
#                             print("Offsetting frame index by {0} for camera {1}".format(OFFSETS.get(cam_name, 0), cam_name))
#                         if adjusted_index not in frame_path_dict:
#                             frame_path_dict[adjusted_index] = {}
#                         root_stub = '/static' + cam_folder.path.split("/static")[1]
#                         frame_path_dict[adjusted_index][cam_name] = os.path.join(root_stub, file.name)

#     return frame_path_dict
import cv2 as cv2
from tqdm import tqdm
def get_frame_path_dict(dset = DSETNAME, frame_path = SYMLINK_DEST_FRAMES, cams = CAMS, local_path = None, cache_path="frame_path_cache.json"):
    """
    Create dictionary of frame paths for each camera, excluding frames that are duplicates
    of their predecessor within the same camera sequence. Results are cached for faster subsequent loads.
    """
    # Try to load from cache first
    if os.path.exists(cache_path):
        with open(cache_path, 'r') as f:
            return {int(k): v for k, v in json.load(f).items()}

    if local_path is None:
        lookup_path = frame_path
    else:
        lookup_path = local_path
        
    frame_path_dict = {}
    last_images = {}
    
    for cam_folder in os.scandir(lookup_path):
        cam_name = cam_folder.name
        if cam_folder.is_dir():
            # print(f"Processing camera {cam_name}")
            sorted_files = sorted(
                [f for f in os.scandir(cam_folder.path) if f.is_file() and f.name.endswith(".jpg")],
                key=lambda x: int(re.search(r"_(\d+)\.jpg$", x.name).group(1))
            )
            
            for file in tqdm(sorted_files, desc=f"Processing camera {cam_name}"):
                match = re.search(r"_(\d+)\.jpg$", file.name)
                if match:
                    index = int(match.group(1))
                    
                    adjusted_index = max(0, index + OFFSETS.get(cam_name, 0))
                    if adjusted_index % 10 != 0:
                        continue
                    current_img = cv2.imread(file.path)
                    if cam_name in last_images:
                        if np.array_equal(current_img, last_images[cam_name]):
                            continue
                            
                    last_images[cam_name] = current_img
                    
                    if adjusted_index != index:
                        print(f"Offsetting frame index by {OFFSETS.get(cam_name, 0)} for camera {cam_name}")
                    if adjusted_index not in frame_path_dict:
                        frame_path_dict[adjusted_index] = {}
                    root_stub = '/static' + cam_folder.path.split("/static")[1]
                    frame_path_dict[adjusted_index][cam_name] = os.path.join(root_stub, file.name)

    # Save to cache
    with open(cache_path, 'w') as f:
        json.dump(frame_path_dict, f)

    return frame_path_dict



FRAME_PATH_DICT = get_frame_path_dict(dset = DSETNAME, frame_path = SYMLINK_DEST_FRAMES, cams = CAMS)
print(FRAME_PATH_DICT.keys())
# Make a local copy of the dataset
# Firefox link to make local image accessible by modifying: about:config
# http://kb.mozillazine.org/Links_to_local_pages_do_not_work
# import shutil
# from tqdm import tqdm

# path_to_local_copy = Path("/cvlabscratch/home/engilber/datasets/SCOUT/local_copy_seq_2")

# max_frame = max(FRAMENUMBER_TO_PATH.keys())

# for frame_num in tqdm(range(0, max_frame + 1, 10)):

# max_frame = max(FRAMENUMBER_TO_PATH.keys())

# for frame_num in tqdm(range(0, max_frame + 1, 10)):
#     # Only process if the frame number is present in the dictionary.
#     if frame_num not in FRAMENUMBER_TO_PATH:
#         continue
#     # Iterate over each camera's frame path for the current frame number.
#     for cam, src_path in FRAMENUMBER_TO_PATH[frame_num].items():
#         # Create a subfolder for the camera if it doesn't already exist.
#         cam_folder = path_to_local_copy / cam
#         cam_folder.mkdir(parents=True, exist_ok=True)
#         # Define the destination path with the original file name.
#         src = Path(src_path)
#         dst = cam_folder / src.name

#         # Skip copying if the destination file already exists.
#         if dst.exists():
#             continue

#         # Copy the file to the local subfolder.
#         shutil.copy(src, dst)