# Generated by Django 4.1.7 on 2023-03-23 08:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0011_auto_20161202_1255"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rectangle_id", models.CharField(max_length=100)),
                ("rotation_theta", models.FloatField()),
                ("Xw", models.FloatField(verbose_name="X World Coordinate")),
                ("Yw", models.FloatField(verbose_name="Y World Coordinate")),
                ("Zw", models.FloatField(verbose_name="Z World Coordinate")),
                ("object_size_x", models.FloatField()),
                ("object_size_y", models.FloatField()),
                ("object_size_z", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_id", models.IntegerField(verbose_name="Frame ID")),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("person_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="View",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_id", models.IntegerField(verbose_name="View ID")),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gtm_hit.frame"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annotation2DView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x1", models.FloatField()),
                ("y1", models.FloatField()),
                ("x2", models.FloatField()),
                ("y2", models.FloatField()),
                (
                    "cuboid_points",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=16
                    ),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twod_views",
                        to="gtm_hit.annotation",
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gtm_hit.view"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="annotation",
            name="frame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gtm_hit.frame"
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gtm_hit.person"
            ),
        ),
    ]
