# Generated by Django 4.1.7 on 2023-03-23 08:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0012_annotation_frame_person_view_annotation2dview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_id", models.IntegerField(verbose_name="Frame ID")),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name="annotation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="annotation2dview",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="view",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="frame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gtm_hit.multiview"
            ),
        ),
        migrations.AlterField(
            model_name="view",
            name="frame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gtm_hit.multiview"
            ),
        ),
        migrations.DeleteModel(
            name="Frame",
        ),
    ]
