# Generated by Django 4.1.7 on 2023-03-23 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0013_multiview_alter_annotation_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiViewFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_id", models.IntegerField(verbose_name="MultiView ID")),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name="annotation",
            name="frame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gtm_hit.multiviewframe"
            ),
        ),
        migrations.AlterField(
            model_name="view",
            name="frame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gtm_hit.multiviewframe"
            ),
        ),
        migrations.DeleteModel(
            name="MultiView",
        ),
    ]
