# Generated by Django 4.1.7 on 2023-03-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0014_multiviewframe_alter_annotation_frame_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiviewframe",
            name="worker_id",
            field=models.ForeignKey(
                default="IVAN",
                on_delete=django.db.models.deletion.CASCADE,
                to="gtm_hit.worker",
            ),
        ),
    ]
