# Generated by Django 4.1.7 on 2023-03-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0015_multiviewframe_worker_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="annotation",
            unique_together={("frame", "person")},
        ),
    ]
