# Generated by Django 4.1.7 on 2023-03-23 15:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0016_alter_annotation_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation2dview",
            name="cuboid_points",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), size=20
            ),
        ),
    ]
