# Generated by Django 4.1.7 on 2023-03-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0017_alter_annotation2dview_cuboid_points"),
    ]

    operations = [
        migrations.RenameField(
            model_name="multiviewframe",
            old_name="worker_id",
            new_name="worker",
        ),
        migrations.RemoveField(
            model_name="view",
            name="id",
        ),
        migrations.AlterField(
            model_name="view",
            name="view_id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="View ID"
            ),
        ),
    ]
