# Generated by Django 4.1.7 on 2023-03-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0018_rename_worker_id_multiviewframe_worker_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="view",
            name="frame",
        ),
    ]
