# Generated by Django 4.1.7 on 2023-03-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0019_remove_view_frame"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="annotation2dview",
            unique_together={("view", "annotation")},
        ),
    ]
