# Generated by Django 4.1.7 on 2023-03-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0020_alter_annotation2dview_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation2dview",
            name="x1",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="annotation2dview",
            name="x2",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="annotation2dview",
            name="y1",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="annotation2dview",
            name="y2",
            field=models.FloatField(null=True),
        ),
    ]
