# Generated by Django 4.1.7 on 2023-03-23 17:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gtm_hit",
            "0021_alter_annotation2dview_x1_alter_annotation2dview_x2_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation2dview",
            name="cuboid_points",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), null=True, size=20
            ),
        ),
    ]
