# Generated by Django 4.1.7 on 2023-03-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0022_alter_annotation2dview_cuboid_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiviewframe",
            name="undistorted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="multiviewframe",
            unique_together={("frame_id", "undistorted", "worker")},
        ),
    ]
