# Generated by Django 4.1.7 on 2023-03-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0023_multiviewframe_undistorted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="annotation_complete",
            field=models.BooleanField(default=False),
        ),
    ]
