# Generated by Django 4.1.7 on 2023-03-30 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0024_person_annotation_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="creation_method",
            field=models.TextField(default="existing_annotation"),
        ),
        migrations.CreateModel(
            name="SingleViewFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_id", models.IntegerField(verbose_name="SingleView ID")),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gtm_hit.view"
                    ),
                ),
            ],
        ),
    ]
