# Generated by Django 4.1.7 on 2023-03-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0025_annotation_creation_method_singleviewframe"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="validated",
            field=models.BooleanField(default=True),
        ),
    ]
